apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fish-website-platform
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  labels:
    app.kubernetes.io/part-of: fish-website
spec:
  project: fish-website-platform
  source:
    repoURL: https://github.com/frozenf1sh/fish-website.git
    targetRevision: main
    path: deploy/clusters/tc-seoul
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
