apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: fish-website
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: fish-website
spec:
  description: fish-website and its private container registry
  sourceRepos:
    - https://github.com/frozenf1sh/fish-website.git
  destinations:
    - namespace: registry
      server: https://kubernetes.default.svc
    - namespace: fish-website
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
