// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"connectrpc.com/connect"
	"context"
	"github.com/frozenfish/fish-website/internal/delivery"
	"github.com/frozenfish/fish-website/internal/domain"
	"github.com/frozenfish/fish-website/internal/identity/application"
	"github.com/frozenfish/fish-website/internal/middleware"
	"github.com/frozenfish/fish-website/internal/repository"
	"github.com/frozenfish/fish-website/internal/usecase"
	"github.com/frozenfish/fish-website/pkg/config"
	"github.com/jackc/pgx/v5/pgxpool"
	"time"
)

// Injectors from wire.go:

func InitializeServer(ctx context.Context, cfg *config.Config) (*Server, error) {
	pool, err := providePGXPool(ctx, cfg)
	if err != nil {
		return nil, err
	}
	ownerAuthenticator := provideOwnerAuthenticator(cfg)
	postgresRepository := providePostgresRepository(pool)
	postRepository := providePostRepository(postgresRepository)
	albumRepository := provideAlbumRepository(postgresRepository)
	imageReferenceRepository := provideImageReferenceRepository(postgresRepository)
	postUsecase := providePostUsecase(postRepository, albumRepository, imageReferenceRepository)
	blogRepository := provideBlogRepository(postgresRepository)
	blogUsecase := provideBlogUsecase(blogRepository, imageReferenceRepository)
	minIOStorage, err := provideMinIOStorage(cfg)
	if err != nil {
		return nil, err
	}
	fileStorage := provideFileStorage(minIOStorage)
	albumUsecase := provideAlbumUsecase(albumRepository, fileStorage, imageReferenceRepository)
	settingsRepository := provideSettingsRepository(postgresRepository)
	settingsUsecase := provideSettingsUsecase(settingsRepository, imageReferenceRepository)
	handler := provideHandler(ownerAuthenticator, postUsecase, blogUsecase, albumUsecase, settingsUsecase)
	interceptor := provideAuthInterceptor(ownerAuthenticator)
	server := NewServer(cfg, pool, handler, interceptor)
	return server, nil
}

// wire.go:

func providePGXPool(ctx context.Context, cfg *config.Config) (*pgxpool.Pool, error) {
	pool, err := pgxpool.New(ctx, cfg.Database.DSN)
	if err != nil {
		return nil, err
	}
	if err := pool.Ping(ctx); err != nil {
		return nil, err
	}
	return pool, nil
}

func providePostgresRepository(pool *pgxpool.Pool) *repository.PostgresRepository {
	return repository.NewPostgresRepository(pool)
}

func providePostRepository(repo *repository.PostgresRepository) domain.PostRepository {
	return repo.NewPostRepository()
}

func provideBlogRepository(repo *repository.PostgresRepository) domain.BlogRepository {
	return repo.NewBlogRepository()
}

func provideAlbumRepository(repo *repository.PostgresRepository) domain.AlbumRepository {
	return repo.NewAlbumRepository()
}

func provideSettingsRepository(repo *repository.PostgresRepository) domain.SettingsRepository {
	return repo.NewSettingsRepository()
}

func provideImageReferenceRepository(repo *repository.PostgresRepository) domain.ImageReferenceRepository {
	return repo.NewImageReferenceRepository()
}

func provideMinIOStorage(cfg *config.Config) (*repository.MinIOStorage, error) {
	return repository.NewMinIOStorage(cfg)
}

func provideFileStorage(storage *repository.MinIOStorage) domain.FileStorage {
	return storage.NewFileStorage()
}

func provideOwnerAuthenticator(cfg *config.Config) *application.OwnerAuthenticator {
	return application.NewOwnerAuthenticator(
		cfg.Auth.OwnerUsername,
		cfg.Auth.AdminPasswordHash,
		cfg.Auth.AdminPassword,
		cfg.Auth.JWTSecret, time.Duration(cfg.Auth.TokenTTLSeconds)*time.Second,
	)
}

func providePostUsecase(repo domain.PostRepository, albumRepo domain.AlbumRepository, imageRefRepo domain.ImageReferenceRepository) *usecase.PostUsecase {
	return usecase.NewPostUsecase(repo, albumRepo, imageRefRepo)
}

func provideBlogUsecase(repo domain.BlogRepository, imageRefRepo domain.ImageReferenceRepository) *usecase.BlogUsecase {
	return usecase.NewBlogUsecase(repo, imageRefRepo)
}

func provideAlbumUsecase(albumRepo domain.AlbumRepository, fileStorage domain.FileStorage, imageRefRepo domain.ImageReferenceRepository) *usecase.AlbumUsecase {
	return usecase.NewAlbumUsecase(albumRepo, fileStorage, imageRefRepo)
}

func provideSettingsUsecase(repo domain.SettingsRepository, imageRefRepo domain.ImageReferenceRepository) *usecase.SettingsUsecase {
	return usecase.NewSettingsUsecase(repo, imageRefRepo)
}

func provideHandler(
	authenticator *application.OwnerAuthenticator,
	postUsecase *usecase.PostUsecase,
	blogUsecase *usecase.BlogUsecase,
	albumUsecase *usecase.AlbumUsecase,
	settingsUsecase *usecase.SettingsUsecase,
) *delivery.Handler {
	return delivery.NewHandler(authenticator, postUsecase, blogUsecase, albumUsecase, settingsUsecase)
}

func provideAuthInterceptor(authenticator *application.OwnerAuthenticator) connect.Interceptor {
	return middleware.NewAuthRequiredInterceptor(authenticator)
}
