apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - app.yaml
images:
  - name: backend
    newName: registry.frozenf1sh.top/fish-website/backend
    newTag: sha-569c1f9f6ee7c71e1b5228f0ca3fd097f01740bb
  - name: frontend
    newName: registry.frozenf1sh.top/fish-website/frontend
    newTag: sha-569c1f9f6ee7c71e1b5228f0ca3fd097f01740bb
