apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - app.yaml
images:
  - name: backend
    newName: registry.frozenf1sh.top/fish-website/backend
    newTag: sha-018378ee6992742db7792eeaf26c8c4739f2704e
  - name: frontend
    newName: registry.frozenf1sh.top/fish-website/frontend
    newTag: sha-018378ee6992742db7792eeaf26c8c4739f2704e
