apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - app.yaml
  - traefik-middleware.yaml
  - network-policy.yaml
images:
  - name: backend
    newName: ghcr.io/frozenf1sh/fish-website/backend
    newTag: v0.2.9
  - name: frontend
    newName: ghcr.io/frozenf1sh/fish-website/frontend
    newTag: v0.2.9
